export const GET_CURRENCIES_ASYNC_REQUEST = "GET_CURRENCIES_ASYNC_REQUEST";

export const GET_CURRENCIES_SUCCESS = "GET_CURRENCIES_SUCCESS";
export const GET_CURRENCIES_FAILURE = "GET_CURRENCIES_FAILURE";
export const GET_CURRENCIES_REQUEST = "GET_CURRENCIES_REQUEST";
